name: orion-decision
tests:
  - name: python 3.6 unittests
    type: tox
    image: ci-py-36
    toxenv: py36
  - name: python 3.7 unittests
    type: tox
    image: ci-py-37
    toxenv: py37
  - name: python 3.8 unittests
    type: tox
    image: ci-py-38
    toxenv: py38
  - name: python 3.9 unittests
    type: tox
    image: ci-py-39
    toxenv: py39
  - name: python 3.10 unittests
    type: tox
    image: ci-py-310
    toxenv: py310
  - name: python 3.11 unittests
    type: tox
    image: ci-py-311
    toxenv: py311
  - name: lint
    type: tox
    image: ci-py-38
    toxenv: lint
