name: symbol-filter
type: test
tests:
  - name: python 3.10 unittests
    type: tox
    python: "3.10"
    toxenv: py310
  - name: python 3.11 unittests
    type: tox
    python: "3.11"
    toxenv: py311
  - name: python 3.12 unittests
    type: tox
    python: "3.12"
    toxenv: py312
  - name: python 3.13 unittests
    type: tox
    python: "3.13"
    toxenv: py313
  - name: lint
    type: tox
    python: "3.10"
    toxenv: lint
