name: taskcluster PR worker
on: [pull_request]
jobs:
  osx-tc-worker-pr:
    runs-on: macos-10.15
    env:
      TASKCLUSTER_ACCESS_TOKEN: ${{ secrets.TASKCLUSTER_ACCESS_TOKEN }}
      TC_WORKER_ID: "gh-orion-pr-${{ github.run_id }}-${{ github.run_attempt }}"
    steps:
      - uses: actions/checkout@v2
        name: clone
      - run: .github/scripts/start-worker.sh
        continue-on-error: true
        name: taskcluster worker
      - run: true
        name: allow failures
