name: taskcluster release worker
on: [release]
jobs:
  osx-tc-worker-release:
    runs-on: macos-13
    env:
      TASKCLUSTER_ACCESS_TOKEN: ${{ secrets.TASKCLUSTER_ACCESS_TOKEN }}
      TC_WORKER_ID: "gh-orion-release-${{ github.run_id }}-${{ github.run_attempt }}"
    steps:
      - uses: actions/checkout@v2
        name: clone
      - run: .github/scripts/start-worker.sh
        continue-on-error: true
        name: taskcluster worker
      - run: true
        name: allow failures
